### ISSUE TITLE
Handling unmatched delims gracefully

### ISSUE THREAD

**Issue by Aerijo** [yitzchak/tree-sitter-latex#13]
There are often cases where the user is defining commands and doesn't have the end in place. Especially common would be a lone `$`, which left unchecked would turn the rest of the file into mathmode for the TextMate grammar. My workaround to that was to let `(?=>})` end mathode as well, so all issues would be confined to the closest group end.

I'm not sure how easily this translates to TS. I haven't tried anything yet, so I've no idea how difficult it will be. It may be that we can rely on Tree-sitter's error recovery.

Actually, a scanner that looks for `$` and advances or `}` and does not advance should work. I'll see how that goes.

**Comment by yitzchak** [comment]
@Aerijo I think #34 made good progress on this. `exit_group` can handle unmatched begin/end in addition to math shifts.

**Comment by yitzchak** [comment]
Closing since `exit` now accounts for non-terminated groups or EOF and `exit_math` accounts for non-terminated TeX math.
