### ISSUE TITLE
Shameless plug

### ISSUE THREAD

**Issue by Aerijo** [yitzchak/tree-sitter-latex#15]
Just wondering if you've seen [my language package](https://atom.io/packages/language-tree-test) for Tree-sitter tests. I find it quite useful, for the colour matching of parentheses and folding.

I didn't want to take the `txt` extension, so I chose `txtt` instead. You'd have to register the extension manually to use it for this project.

**Comment by yitzchak** [comment]
Cool! Renamed all the tests.
