### ISSUE TITLE
Optional text group

### ISSUE THREAD

**Issue by Aerijo** [yitzchak/tree-sitter-latex#3]
Currently it's detecting `foo[bar]wibble` as an optional text group (intentionally). Should this be restricted to only following commands / environment openings? I feel that treating all `[` as starting an optional group is too inclusive, especially considering optional groups aren't special in regular text (such as in the test). 

Restricting it may possibly miss some, but will have far fewer false positives in comparison.

**Comment by yitzchak** [comment]
I think you are probably right since LaTeX doesn't see unmatched square brackets as an error.
