### ISSUE TITLE
Naming of control sequences

### ISSUE THREAD

**Issue by Aerijo** [yitzchak/tree-sitter-latex#5]
Control sequences can be split into two categories: words and symbols. For users (syntax highlighting in particular) they often want to highlight all of these in one colour, or all words in one and symbols in another, and have exceptions for specific rules.

On the Atom side, we can define a scope for every rule we currently define separately (`textbf`, `footnote`, `documentclass`, `usepackage`,...), but that feels awkward. Instead, maybe this package could  have `command` or `control_sequence` as a parent rule for all the ones currently called `..._token`. I don't think differentiating words and symbols here is strictly necessary, as the Atom side can use regex to further classify nodes (though it should be relatively easy to do on this end). 

PS: These issues I'm opening don't need to be resolved urgently, I just want to know what the vision is for this package / make sure we all agree on what it should be.

**Comment by yitzchak** [comment]
I would like to have simplest grammar that still supports syntax highlighting such as `\emph{foo}` with the `foo` text actually styled. The CSS selectors on the Atom side seem to limited to direct children not siblings, etc. To me this means we need at least the following conceptual s-expr.

```
(emph
  (token)
  (text_group
    (open_brace)
    (text)
    (close_brace)))
```

**Comment by Aerijo** [comment]
That looks fine, we can target `token` directly. It's when we have `emph_token`, `textit_token`, ..., that it becomes bothersome. We can hold of on this for now; there are still a lot of other things to do.
